@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@hcl.com",
"password":"123456"
}
###
POST {{HOST}}/users HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"usertype":"1",
"lastname":"dolor",
"firstname":"voluptate",
"password":"ucode1234",
"email":"nostrud@ucode.ai0",
"mobile":"reprehenderit9"
}

###

#MAIN REGISTRATION for NODEJS VERSION
POST {{HOST}}/users/reg HTTP/1.1
content-type: application/json
    
{
"email":"test@ucode.ai",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"mobile":"60176408250"
}
###
#MAIN REGISTRATION for Java Spring boot
POST {{HOST}}/reg HTTP/1.1
content-type: application/json
 
{
"email":"test@hcl.com",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"mobile":"60176408250"
}
###

GET {{HOST}}/users? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users?usertype=1&lastname=dolor&firstname=voluptate&email=nostrud@uc&mobile=reprehende HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"usertype":"1",
"lastname":"dolor",
"firstname":"voluptate",
"password":"ucode1234",
"email":"nostrud@ucode.ai0",
"mobile":"reprehenderit9"
}
###
PATCH {{HOST}}/users/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"usertype":"1",
"lastname":"dolor",
"firstname":"voluptate",
"password":"ucode1234",
"email":"nostrud@ucode.ai0",
"mobile":"reprehenderit9"
}
###
DELETE {{HOST}}/users/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
